### PR TITLE
Add protocolize

### PR DESCRIPTION
**Pull request by Exceptionflug**
Protocolize is a protocol framework for BungeeCord, ready to be added to the list.

### CODE REVIEW

**Comment by NotMyFault** [comment]
Never heard of this before, but Velocity >

**Comment by Exceptionflug** [comment]
This may be true but BungeeCord is still the most used proxy software.

**Comment by mbax** [comment]
> This may be true but BungeeCord is still the most used proxy software.

and PEX was the most-used permissions plugin for a long time while being full of bugs with better alternatives available. Doesn't mean PEX or a PEX accessory plugin should have ever been put on an "awesome" list! 😁

**Comment by Exceptionflug** [comment]
Following your logic, the same would be apply for Bukkit / Spigot as software itself which is definetly not bug free and has definetly not a good API either.

**Comment by KotlinFactory** [comment]
Also, there are other BungeeCord plugins listed on this readme, so not listing protocolize here because it does not (yet?) support Velocity is not a good point.

**Comment by mbax** [comment]
> Following your logic, the same would be apply for Bukkit / Spigot as software itself which is definetly not bug free and has definetly not a good API either.

Following my logic *to an extreme*, sure. But I never had to maintain a six page document detailing bugs in Bukkit that would regularly break experiences for users. 😛

**Comment by JRoy** [comment]
image

**Comment by Aberdeener** [comment]
Screen Shot 2021-02-02 at 8 53 09 AM

**Comment by Exceptionflug** [comment]
> I never had to maintain a six page document detailing bugs in Bukkit that would regularly break experiences for users. 😛

Cool. Just take a look at the implementation or even the underlying server implemention. And for the last, you don't even have to maintain a six page document detailing bugs and stuff, Mojang does this for you: https://bugs.mojang.com/projects/MC/issues/MC-147122?filter=allopenissues 😛

**Comment by Exceptionflug** [comment]
> 
> 
> Screen Shot 2021-02-02 at 8 53 09 AM

Thank you for mentioning this

**Comment by kadenscott** [comment]
> And for the last, you don't even have to maintain a six page document detailing bugs and stuff, Mojang does this for you: https://bugs.mojang.com/projects/MC/issues/MC-147122?filter=allopenissues 😛

none of these have anything to do with bukkit tho?

**Comment by Exceptionflug** [comment]
> none of these have anything to do with bukkit tho?

For the end users of course: It's all in one file and represents one software solution.

**Comment by mbax** [comment]
> > I never had to maintain a six page document detailing bugs in Bukkit that would regularly break experiences for users. 😛
> 
> Cool. Just take a look at the implementation or even the underlying server implemention. And for the last, you don't even have to maintain a six page document detailing bugs and stuff, Mojang does this for you: https://bugs.mojang.com/projects/MC/issues/MC-147122?filter=allopenissues 😛

I *wrote* some of that API and implementation, so I think I'm pretty well versed in it thanks.

**Comment by mbax** [comment]
> What exactly has this to do with the PR?

I dunno, Exceptionflug went off on a tangent about Bukkit bugs and is now suggesting the Mojang JIRA is a "all in one file" "one software solution" for... documenting Bukkit bugs?

**Comment by kadenscott** [comment]
> I mean you started the discussion whether Velocity or BungeeCord is the better Proxy.
> But that is totally off-topic, as far as I'm concerned.

no, NMF (not mbax, evidently) made a throwaway joke, it aint that serious

**Comment by mbax** [comment]
> I mean you started the discussion whether Velocity or BungeeCord is the better Proxy.
> But that is totally off-topic, as far as I'm concerned.

No, I didn't?

**Comment by KotlinFactory** [comment]
> > This may be true but BungeeCord is still the most used proxy software.
> 
> and PEX was the most-used permissions plugin for a long time while being full of bugs with better alternatives available. Doesn't mean PEX or a PEX accessory plugin should have ever been put on an "awesome" list! 😁

?

**Comment by mbax** [comment]
> > > This may be true but BungeeCord is still the most used proxy software.
> > 
> > 
> > and PEX was the most-used permissions plugin for a long time while being full of bugs with better alternatives available. Doesn't mean PEX or a PEX accessory plugin should have ever been put on an "awesome" list! 😁
> 
> ?

Look two comments and several days prior.

**Comment by KotlinFactory** [comment]
I did. But that didn't start a discussion.

**Pull request closed without merging**
