### PR TITLE
add some server management software+ add some handy libraries

### PR DESCRIPTION
**Pull request by superbiebel**
- added the "Server Management Software" category
- added subservers
- added cloudnet

### CODE REVIEW

**Comment by superbiebel** [comment]
gonna add a few things still so dw, will mark when ready

**Comment by clrxbl** [comment]
Travertine doesn't fit the list in my opinion. The majority does not care about 1.7 support and the project is barely maintained.

**Comment by superbiebel** [comment]
im sure there are more server management projects out there so this is just a start

**Comment by superbiebel** [comment]
ready to merge

**Comment by kadenscott** [comment]
If I'm being honest, I don't think this list is suited for the software in this PR. In my eyes, awesome-minecraft should be for mainstream, popular tools applicable to many servers. These are pieces of software I personally have never heard of before. 
Not saying anything against the software in particular, but, especially when it comes to the kind of software you're suggesting, most large servers have a custom system developed to their specific needs.

**Comment by NotMyFault** [comment]
I'm not a fan either, those "server management software" sound pretty niche and don't target a proper audience.

**Comment by superbiebel** [comment]
> If I'm being honest, I don't think this list is suited for the software in this PR. In my eyes, awesome-minecraft should be for mainstream, popular tools applicable to many servers. These are pieces of software I personally have never heard of before.
> Not saying anything against the software in particular, but, especially when it comes to the kind of software you're suggesting, most large servers have a custom system developed to their specific needs.

These pieces of software have a very extensive api, which allows enormous customization without having to write from scratch.
if u don't like the tools then just close the PR, no hard feelings.

**Comment by Citymonstret** [comment]
This is less about what we like and more about what the bigger community values. I am very open to feedback.

**Comment by superbiebel** [comment]
well it's a choice u guys have to make

**Comment by Citymonstret** [comment]
It seems the general consensus is that these particular projects don't belong on the list.

**Pull request closed without merging**
